name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Checkout mã nguồn từ repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Bước 2: Đăng nhập vào Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Debug DOCKER_USERNAME
        run: echo ${{ secrets.DOCKER_USERSNAME }}


      # Bước 3: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERSNAME }}/simple-nodejs-web:latest .

      # Bước 4: Push Docker image lên Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERsNAME }}/simple-nodejs-web:latest
